# Generated by Django 4.1.7 on 2023-05-03 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(choices=[('MAC', 'Mac and Cheese'), ('PIZ', 'Pizza'), ('PAS', 'Pasta')], max_length=3)),
                ('cook_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('est_end_time', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.meal')),
            ],
        ),
    ]
