# Generated by Django 4.2 on 2023-05-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(choices=[('MAC', 'Mac & Cheese'), ('PIZ', 'Pizza'), ('PAS', 'Pasta'), ('NAC', 'Nacho'), ('SUB', 'Sub Sandwich')], max_length=3)),
                ('cook_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('est_end_time', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee_app.meal')),
            ],
        ),
    ]
