# Generated by Django 4.2 on 2023-05-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cook_time',
            field=models.IntegerField(),
        ),
    ]
