# Generated by Django 4.1.7 on 2023-05-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('mealId', models.BigAutoField(primary_key=True, serialize=False)),
                ('mealName', models.CharField(max_length=255)),
                ('mealPrepTime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderNumber', models.IntegerField()),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField()),
                ('isComplete', models.BooleanField()),
            ],
        ),
    ]
