# Generated by Django 4.1.7 on 2023-03-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('orderNumber', models.IntegerField()),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('isComplete', models.BooleanField()),
            ],
        ),
    ]
